# for setting up a k8s deployment
# reminder: don't use tabs for yaml!

# client-frontend
# client-frontend_web is what I named my image via docker build
# k so since client-frontend has docker-compose.yml, it seems to be recommended to use kompose to convert it to k8s deployment yml files.
# ---
# apiVersion: v1
# kind: Pod
# metadata:
  # name: client-frontend
# spec:
  # containers:
    # - name: client-frontend
      # image: client-frontend_web
      # ports:
        # - containerPort: 5000



# observer
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: observer



# timekeeper
---
apiVersion: v1
kind: Pod
metadata:
  name: timekeeper
spec:
  containers:
    - name: timekeeper
      image: timekeeper
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent